services:
  gz-sim:
    devices:
      - /dev/dri:/dev/dri
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command:
      - ros2
      - launch
      - curtmini_piper_gz_sim
      - simulation.launch.py
      - gui:=true
      - use_rviz:=false
      - world:=${SIM_WORLD:-curtmini_piper}
      - use_hokuyo:=${SIM_USE_HOKUYO:-true}
